name: Feature Request
description: File a feature request
title: "[Brief feature description]"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        This feature request will be analysed, put into the correct project/repository and processed by our team. 
        Please be as much accurate as possible to optimise our response time.
  - type: dropdown
    id: context
    attributes:
      label: Context/theme
      description: To which context/theme this feature applies?
      multiple: true
      options:
        - Integrated (OceanOPS) 
        - Argo 
        - DBCP 
        - SOT 
        - GO-SHIP 
        - OceanSITES 
        - GLOSS 
        - OceanGliders 
        - Other (please specify)
    validations:
      required: true
  - type: input
    id: context-other
    attributes:
      label: Other context (if applicable)
      description: If 'Other' selected above, please specify it here.
  - type: textarea
    id: description
    attributes:
      label: Description of the desired feature
      description: A clear and concise description of what the missing feature is.
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other information about the feature request here.
  - type: markdown
    id: priority
    attributes:
      value: |
        ## Priority
        If blocking, please select the corresponding label.
  - type: markdown
    id: screenshots
    attributes:
      value: |
        ## Screenshot
        If applicable, add screenshots as comment to this issue to help explain your problem.
